version: '3.8'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

